### ISSUE TITLE
python not importing functions from other python files

### ISSUE THREAD

**Issue by chadyoungdell** [chadyoungdell/python.function.example.snap#2]
https://pastebin.com/yv1igsNu

admin@BDPLB02:~ $ python-function-example.hello"
Traceback (most recent call last):
  File "/snap/python-function-example/x1/bin/hello", line 3, in <module>
    import message
ImportError: No module named 'message'
admin@BDPLB02:~ $'''

**Comment by chadyoungdell** [comment]
after latest merge - error still exists

admin@BDPLB02:~ $ python-function-example.hello
Traceback (most recent call last):
  File "/snap/python-function-example/x1/./hello.py", line 3, in <module>
    import message.py
ImportError: No module named 'message.py'; 'message' is not a package
admin@BDPLB02:~ $

**Comment by chadyoungdell** [comment]
The code in the repo is now working will pretty it up shortly.
